config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "rooms#index"

  resources :rooms

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  default_scope { order(created_at: :desc).limit(50) }
  validates :body, presence: true
  
  belongs_to :user
  belongs_to :room

  after_create_commit :broadcast_message

  private

  def broadcast_message
    MessageBroadcastJob.perform_later(self)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  scope :visible, -> { where(hidden: false) }
  validates :title, presence: true

  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, :ensure_admin, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.try(:admin?)
      @rooms = Room.page params[:page]
    else
      @rooms = Room.visible.page params[:page]
    end
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:notice] = "Room successfully created!"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
    ensure_admin if @room.hidden? && current_user
  end

  def edit;  end

  def update
    if @room.update(room_params)
      flash[:notice] = "Room successfully updated!"
      redirect_to rooms_path
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    flash[:notice] = "#{@room.title} room successfully deleted!"
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit(:title, :hidden)
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def ensure_admin
    unless current_user.admin?
      flash[:alert] = "This action available ony for admins!"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def human_boolean(boolean)
    boolean ? "Yes" : "No"
  end

  def submit_btn_text(object)
    @room.new_record? ? "Create" : "Update"
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def user_name(message)
    "@" + message.user.email.split('@')[0]
  end

  def message_date_time(message)
    date_fromat = "%B %d, %Y | " if message.created_at < (DateTime.now - 1.day)
    message.created_at.strftime("#{date_fromat}%I:%M%p")
  end
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-light
  .container
    = link_to root_path, class: "navbar-brand" do
      = image_tag "logo.svg", alt: 'logo', class: 'logo'
    %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarNavDropdown.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        - if current_user
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "#", role: "button"}
              = current_user.email
            .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              - if current_user.admin?
                = link_to "Create room", new_room_path, class: "dropdown-item"
              = link_to "Edit profile", edit_user_registration_path, class: "dropdown-item"
              .dropdown-divider
              = link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item"
        - else
          %li.nav-item
            = link_to "Login", new_user_session_path, class: "nav-link"
          %li.nav-item
            = link_to "Register", new_user_registration_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    - if current_user
      %meta{name: "current_user", data: {id: current_user.id}}
    %title Chatty
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render "layouts/navbar"
    .container
      - flash.each do |key, value|
        .alert.alert-dismissible.fade.show{ class: "alert-#{key}", role: "alert" }
          = value
          %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
      = yield

app/views/messages/_message.html.haml
.message
  %span.message__author
    = "#{user_name(message)}:"
  %span.message__body= message.body
  %time.message__time= message_date_time(message)

app/views/rooms/_form.html.haml
= simple_form_for @room do |f|
  = f.input :title, as: :string
  = f.input :hidden
  = f.button :submit, submit_btn_text(@room), class: "btn btn-primary"

app/views/rooms/_room.html.haml
%tr.room
  %td
    = link_to room.title, room_path(room)
  - if current_user && current_user.admin?
    %td
      = human_boolean(room.hidden?)
    %td
      = link_to "Edit", edit_room_path(room)
      |
      = link_to "Delete", room_path(room), method: :delete

app/views/rooms/edit.html.haml
.row.justify-content-center
  .col-6
    %h2.text-center= "Edit #{@room.title} room"
    =render "rooms/form"

app/views/rooms/index.html.haml
%h2.text-center
  Chat rooms:
.row.justify-content-center
  .col-6
    %table.table.table-bordered
      %thead
        %tr
          %th Title
          - if current_user.try(:admin?)
            %th Is hidden?
            %th Actions
      %tbody
      = render @rooms
.row.justify-content-center
  = paginate @rooms

app/views/rooms/new.html.haml
.row.justify-content-center
  .col-6
    %h2.text-center Create new room
    = render "rooms/form"

app/views/rooms/show.html.haml
.row.justify-content-center
  .col-9
    %h1.text-center
      = @room.title + " room"
    - if current_user
      #messages{"data-room-id" => @room.id}
        = render @room.messages.includes(:user).reverse
      
      = form_with url: "#", html: {id: "new_message", autocomplete: "off"} do |f|
        .input-group.mb-3
          = f.text_field :body, id: "message_body", class: "form-control", placeholder: "Message text..."
          .input-group-append
            = f.submit "Send", class: "btn btn-primary send-message-btn"
    - else
      %p.text-center
        = link_to "You must login to see and send messages", new_user_session_path